#!/bin/sh

#if you want to use pre-commit validations copy this file to .git/hooks/ inside your project folder

container=`docker ps --format "{{.Names}}" --filter "name=jwt-manager-php-lib"`

if [ -z $container ]
    then
        echo "Your container name is not valid. Try put jwt-manager-php-lib on the end of container's name."
fi

docker exec -w /var/www/html "$container" composer lint
if [ $? != 0 ]; then
    echo "Fix the PHP sintax errors before commit."
    exit 1
fi

echo "Running Code Sniffer..."
docker exec $container ./vendor/bin/phpcs

if [ $? != 0 ]
then
    echo "Fix the Code Sniffers errors before commit."
    exit 1
fi

echo "Running PHP Stan..."
docker exec $container ./vendor/bin/phpstan analyse

if [ $? != 0 ]
then
    echo "Fix the PHP Stan errors before commit."
    exit 1
fi

echo "Running Unit Tests..."
docker exec $container php -d xdebug.mode=coverage vendor/bin/phpunit --configuration phpunit.xml --coverage-clover=coverage/coverage.xml -d memory_limit=1024M

if [ $? != 0 ]
then
    echo "Fix the Unit Tests errors before commit."
    exit 1
fi

echo "Checking Unit Coverage..."
docker exec $container php contrib/coverage-checker.php coverage/coverage.xml 100

if [ $? != 0 ]
then
    echo "Raise the Unit Coverage to 100% before commit."
    exit 1
fi

exit $?